export const globalcolor = {
  ImageBaseUrl: 'https://assets-beta.diskounto.com/',
  PrimaryColor: '#FD7729',
  PrimaryColorLight: '#ffd591',
  SeconderFontColor: '#6A6A49',
  ProgessColor: '#531dab',
  ProgessColorLight: '#d3adf7',
  FontBlack: '#000000',
  SeconderColor: '#2C2C2C',
  Font: 'Lato-Regular',
  FontLight: 'Lato-Light',
  GradientSeconder: '#FF9626',
  Textcolor: '#ffffff',
  BackgroundColor: '#FFF5EA',
  PlaceHolderColor: '#666666',
  Separator: '#F0F0F0',
  Successcolor: '#389e0d',
  SuccessLight: '#b7eb8f',
  Errorcolor: '#dc3545',
  LightError: '#ffa39e',
  BorderColor: '#C4C4C4',
  AlertBorder: '#ffe58f',
  AlertBackground: '#fffbe6',
};
